
env:
  - DB=sqlite
before_script:
  - bundle exec sunspot-solr start -p 8983
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec rake sunspot:solr:reindex
  - bundle exec cucumber
  - bundle exec rake spec
after_script:
  - bundle exec sunspot-solr stop

language: ruby
rvm:
  - 2.2.2

addons:
    code_climate:
        repo_token: 14403f904d69e9fa8b17ba47a8f76fcb2cc773bde214d6c6c27313419b0647e8
